### PR TITLE
Add missing options for HA mode

### PR DESCRIPTION
**Pull request by MiLk**
This adds configurable variables for `redirect_addr` and `cluster_addr` which are needed in certain cases for the [HA mode](https://www.vaultproject.io/docs/concepts/ha.html).

I've added the options only to the backends supporting HA mode.

### CODE REVIEW

**Comment by MiLk** [comment]
@kbrebanov Could you take a look at this PR? Thanks :)

**Comment by kbrebanov** [comment]
Can you use empty string '' as the default value and updates your conditions accordingly to be consistent with the rest of the variables that default to being undefined (empty string)?

Also, can you add the variables to the **defaults/main.yml** file?

**Comment by MiLk** [comment]
Done

**Comment by kbrebanov** [comment]
Hmm.. Now I'm wondering if it would make more sense to create separate variables for each backend type. Like:

vault_backend_consul_redirect_addr
vault_backend_consul_cluster_addr
vault_backend_etcd_redirect_addr
vault_backend_etcd_cluster_addr
vault_backend_zookeeper_redirect_addr
vault_backend_zookeeper_cluster_addr

Looks like you can have a non-HA and HA backend being used in the same setup. If someone uses consul for their non-HA backend and etcd for their HA backend, for example, then I would not want those variables to affect both backends.

**Comment by MiLk** [comment]
This role is currently not supporting an `ha_backend`.

I would prefer keeping the variables as they are, but use them only in the `ha_backend` if both `backend` and `ha_backend` are defined.
But that would be for a separate PR.

What do you think?

**Comment by kbrebanov** [comment]
The docs state that if you specify an HA capable backend for `backend`, then it will use HA. So the role supports HA backends simply by specifying an HA capable backend in the `backend` variable.

The current role also has these variables:

`vault_backend_consul_advertise_addr`
`vault_backend_etcd_advertise_addr`
`vault_backend_zookeeper_advertise_addr`
`vault_backend_s3_advertise_addr`
`vault_backend_mysql_advertise_addr`

The description for these variables in the README is:

`For backends that support HA, this is the address to advertise to other Vault servers in the cluster for request forwarding`

`cluster_addr` has the same description so, I'm guessing the name of the option was changed at some point. I can't seem to find references to `advertise_addr` in the current documentation.

So looks like there is some cleanup and renaming of variables to do.

I still think there should be separate variables per backend like stated it my previous comment and probably also remove all the `vault_backend_*_advertise_addr` variables if they are not used anymore.

**Comment by MiLk** [comment]
My point was that you currently cannot enable a backend without HA and a backend with HA, because you would need to have a `backend` section (which is already supported) and an `ha_backend` section (which is currently not supported).

It seems `redirect_addr` is the new name for `advertise_addr`.
Anyway, I will rename the variables to be consistent tomorrow at work.

**Comment by MiLk** [comment]
I've renamed the variables and removed the `advertise_addr` variables.

**Pull request merged**
